# Generated by Django 2.2.1 on 2019-07-15 02:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190715_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='frame_rate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='timecodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
